[package]
name = "kernel_resolution"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
paste = "1.0.15"

[dependencies.pyo3]
version = "0.25"
features = [
    "abi3",
    "extension-module",
]
