name: Wheels
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish wheels'
        required: true
        default: false
        type: boolean

jobs:
  Build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==3.0.0b5

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      if: matrix.os == 'macos-13'
      env:
        CIBW_ENVIRONMENT: 'MACOSX_DEPLOYMENT_TARGET=13.0'

    - name: Upload artifacts
      if: (github.ref == 'refs/heads/master') && inputs.publish
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl
